language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
install:
<<<<<<< HEAD
  - make build
=======
  - make
>>>>>>> Add support for codecov
  - pip install codecov
script:
  - make test
  - coverage run -m unittest tests/*.py
after_success:
  - codecov
